apiVersion: v1
kind: Pod
metadata:
  name: gpu-rocm-test
spec:
  containers:
    - name: gpu-sim
      image: public.ecr.aws/docker/library/busybox:latest
      command: [sh, -c, "echo Hello from fake GPU node && sleep 3600"]  # yamllint disable-line rule:quoted-strings
      resources:
        limits:
          amd.com/gpu: 1
  nodeSelector:
    hardware-type: gpu
  tolerations:
    - key: gpu
      operator: Equal
      value: true
      effect: NoSchedule
